---
title: "第4章 効果量(2) 1節"
author: "kazutan"
date: "2015年05月05日"
output: html_document
---

## このドキュメントについて
このドキュメントは、[続・『続・心理統計学の基礎』（南風原朝和 著）読書会](http://www.urano-ken.com/blog/2015/03/28/dokushokai2/)について作成した第4章1節のメモという位置づけです。ただこのドキュメントのみでは意味が通らないかと思いますので、[続・心理統計学の基礎](http://www.yuhikaku.co.jp/books/detail/9784641220416)と共にご覧ください。

## 1.重回帰分析における効果量

### 重相関係数の検定の検定力を規定する効果量
重相関係数$R$の有意性検定は以下の検定統計量$F$は、以下から算出されます:

$$
\begin{eqnarray}
F = \frac{R^2}{1-R^2} \times \frac{N-p-1}{p}
\end{eqnarray}
$$

この検定統計量$F$は自由度$(p,N-p-1)$のF分布に従います。なお$N$はサンプルサイズであり、**$p$はこの独立変数の値を所与(与えられたもの)としたときの従属変数の条件付き分布について、当分散の正規性を仮定**しています。これが偽であるときは自由度$(p,N-p-1)$の非心$F$分布に従い、非心度は以下から算出されます:

$$
\begin{eqnarray}
\lambda = \frac{\rho^2}{1-\rho^2} \times N
\end{eqnarray}
$$

ここで、$\rho$は母集団重相関係数この非心度から$N$を取り除いた部分が、重相関係数の母集団効果量となります:

$$
\begin{eqnarray}
\theta^2 = \frac{\rho^2}{1-\rho^2}
\end{eqnarray}
$$

### 追加変数の効果の検定の検定力を規定する効果量
ここで対象としているのはいわゆる$\Delta R^2$であり、階層的重回帰分析などで議論される指標になります。独立変数を追加した際の効果を検定する統計量は以下から算出されます:

$$
\begin{eqnarray}
F = \frac{\Delta R^2}{1-R_{after}^2} \times \frac{N-p-1}{q}
\end{eqnarray}
$$

ここで、$R_{after}^2$は変数追加後の決定係数で、$\Delta R^2$は変数を追加したことによる$R^2$の増分($R_{after}^2 - R_{before}^2$)です。あと自由度が違いますので注意してください(第一自由度が追加投入した変数の数で$p$はトータルの変数数)。なお、**$q=1$(追加変数がひとつ)の場合、この検定はその追加した変数の偏回帰係数の有意性と一致**します。

なおこれも、母集団における決定係数の増分$\Delta \rho^2$が0であるという帰無仮説が偽であるときは、自由度$(q,N-p-1)$非心$F$分布になります:

$$
\begin{eqnarray}
\lambda = \frac{\rho^2}{1-\rho_{after}^2} \times N
\end{eqnarray}
$$

ここからNの要素を排除した、追加変数の効果の検定の検定力を規定する母集団効果量は以下の式より算出されます:

$$
\begin{eqnarray}
\theta'^2 = \frac{\rho^2}{1-\rho_{after}^2}
\end{eqnarray}
$$

### 解釈の観点からの効果量
省略します。テキストの通りです。

### 部分決定係数
上述の$\Delta rho^2$は**その追加変数から他の変数(事前に投入されていた変数)の影響を取り除いたもの**であり、部分相関係数$\rho_{part}$の2乗です。これを**部分決定係数**と呼びます:

$$
\begin{eqnarray}
\rho_{part}^2 = \Delta \rho^2 = \rho_{after}^2 - \rho_{before}^2
\end{eqnarray}
$$

### 偏決定係数
偏決定係数と決定係数、部分決定係数には以下のような関係があります:

$$
\begin{eqnarray}
\rho_{partial}^2 = \frac{\Delta \rho^2}{1-\rho_{before}^2} = \frac{\rho_{after}^2 - \rho_{before}^2}{1-\rho_{before}^2}
\end{eqnarray}
$$

これの意味するところは、「変数の追加によって、追加前に説明できていなかった残差分散のうち何%を説明できたか」です。イメージはテキストの数式(4.10)を参照してください。

### 異なる効果量の間の関係
基本省略します。非心度$\lambda$と母集団偏決定係数の関係は以下のとおりです:

$$
\begin{eqnarray}
\lambda = \frac{\rho_{partial}^2}{1-\rho_{partial}^2} \times N
\end{eqnarray}
$$

### 標準偏回帰係数
ここでは省略します。テキストの通りです。

### 効果量の点推定
通常は自由度調整済み決定係数を使用します:

$$
\begin{eqnarray}
R_{adj}^2 = 1-\frac{N-1}{N-p-1}(1-R^2)
\end{eqnarray}
$$

他の指標の推定量算出ではこの$R_{adj}^2$を使えば計算していくことができますので省略します。

### 重相関係数と決定係数の信頼区間
理論的な部分は第3章を参考にしてください。テキストに書いてある数値を使ってRで計算してみます:
```{r}
#パラメータ設定
N <- 100
p <- 3
R_sq <- .5 #決定係数
alp <- .05

Fvalue <- (R_sq/(1-R_sq))*((100-3-1)/3)
Fvalue

# 非心値の上限・下限を求めます
# MBESSパッケージを使います
library(MBESS)
lambdaaaa <- conf.limits.ncf(F.value=Fvalue,df.1=p,df.2=N-p-1,conf.level=1-alp)
lambdaaaa

# あとは母集団決定係数の95%信頼区間を算出します
rho2_L <- lambdaaaa$Lower.Limit / (N+lambdaaaa$Lower.Limit)
rho2_U <- lambdaaaa$Upper.Limit / (N+lambdaaaa$Upper.Limit)
c(rho2_L,rho2_U)
```

### 偏決定係数の信頼区間
省略します。$F$値の算出方法がちょっと変わるだけで、あとはすぐ上と同じです。

### 標準偏回帰係数の信頼区間
省略します。
